defaultNetwork: localhost
networks:
  localhost:
    nodes:
      - { id: 0, account: 3, ipv4Addr: host.docker.internal }
  stabletestnet:
    nodes:
      - { id: 0, account: 3, ipv4Addr: 34.94.106.61 }
